services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        fromService: resume-matcher
        type: envVar
      - key: FLASK_ENV
        value: production
